# Generated by Django 3.2.16 on 2025-01-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='profession_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='graphs/')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_ux_project.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('average_salary', models.FloatField()),
                ('vacancy_count', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('skill', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_count', models.IntegerField(blank=True, null=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_ux_project.profession')),
            ],
        ),
    ]
