# Generated by Django 3.2.16 on 2025-01-11 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='CityShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('vacancy_share', models.FloatField(verbose_name='Доля вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=255, verbose_name='Навык')),
                ('skill_count', models.IntegerField(verbose_name='Количество упоминаний')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('vacancy_count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
        ),
        migrations.RemoveField(
            model_name='profession',
            name='image',
        ),
        migrations.AddField(
            model_name='uploadedgraph',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.TextField(verbose_name='Описание профессии'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название профессии'),
        ),
        migrations.AlterField(
            model_name='uploadedgraph',
            name='image',
            field=models.ImageField(upload_to='graphs/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='uploadedgraph',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_ux_project.profession', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='uploadedgraph',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок графика'),
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.AddField(
            model_name='vacancytrend',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_ux_project.profession', verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='skill',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_ux_project.profession', verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='salarytrend',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_ux_project.profession', verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='cityshare',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_ux_project.profession', verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='citysalary',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_ux_project.profession', verbose_name='Профессия'),
        ),
    ]
