# Generated by Django 3.2.16 on 2025-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0002_auto_20250111_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityVacancyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='Город')),
                ('vacancy_share', models.FloatField(verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доля вакансий по городам',
            },
        ),
        migrations.CreateModel(
            name='SalaryDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Динамика зарплат',
                'verbose_name_plural': 'Динамика зарплат',
            },
        ),
        migrations.CreateModel(
            name='VacancyDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Год')),
                ('vacancy_count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Динамика вакансий',
                'verbose_name_plural': 'Динамика вакансий',
            },
        ),
        migrations.AlterModelOptions(
            name='citysalary',
            options={'verbose_name': 'Зарплата по городам', 'verbose_name_plural': 'Зарплата по городам'},
        ),
        migrations.RemoveField(
            model_name='citysalary',
            name='profession',
        ),
        migrations.AlterField(
            model_name='citysalary',
            name='city',
            field=models.CharField(max_length=100, unique=True, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='TopSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=100, verbose_name='Навык')),
                ('skill_count', models.IntegerField(verbose_name='Количество упоминаний')),
            ],
            options={
                'verbose_name': 'Топ навыков',
                'verbose_name_plural': 'Топ навыков',
                'unique_together': {('year', 'skill')},
            },
        ),
    ]
