# Generated by Django 3.2.16 on 2025-01-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0003_auto_20250111_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarytrend',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='uploadedgraph',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='vacancytrend',
            name='profession',
        ),
        migrations.DeleteModel(
            name='CityShare',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='SalaryTrend',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='UploadedGraph',
        ),
        migrations.DeleteModel(
            name='VacancyTrend',
        ),
    ]
