# Generated by Django 3.2.16 on 2025-01-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0004_auto_20250111_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topskills',
            old_name='skill_count',
            new_name='count',
        ),
    ]
