# Generated by Django 3.2.16 on 2025-01-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0006_chartimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartimage',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='chartimage',
            name='chart_type',
            field=models.CharField(max_length=50, verbose_name='Тип графика'),
        ),
        migrations.AlterUniqueTogether(
            name='chartimage',
            unique_together={('chart_type', 'year')},
        ),
    ]
