# Generated by Django 3.2.16 on 2025-01-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0007_auto_20250111_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydynamic',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='vacancydynamic',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='salarydynamic',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='vacancydynamic',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
