# Generated by Django 3.2.16 on 2025-01-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0008_auto_20250114_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Зарплата (Востребованность)',
                'verbose_name_plural': 'Зарплаты (Востребованность)',
            },
        ),
        migrations.CreateModel(
            name='DemandVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('vacancy_count', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Вакансия (Востребованность)',
                'verbose_name_plural': 'Вакансии (Востребованность)',
            },
        ),
    ]
