# Generated by Django 3.2.16 on 2025-01-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0009_demandsalary_demandvacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citysalary',
            options={'verbose_name': 'Зарплата по городам', 'verbose_name_plural': 'Зарплаты по городам'},
        ),
        migrations.AlterModelOptions(
            name='cityvacancyshare',
            options={'verbose_name': 'Доля вакансий по городам', 'verbose_name_plural': 'Доли вакансий по городам'},
        ),
        migrations.AlterField(
            model_name='citysalary',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='cityvacancyshare',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
    ]
