# Generated by Django 3.2.16 on 2025-01-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0010_auto_20250114_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCitySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Зарплата по городам (География)',
                'verbose_name_plural': 'Зарплаты по городам (География)',
            },
        ),
        migrations.CreateModel(
            name='GeoCityVacancyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('vacancy_share', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам (География)',
                'verbose_name_plural': 'Доли вакансий по городам (География)',
            },
        ),
        migrations.AlterModelOptions(
            name='citysalary',
            options={'verbose_name': 'Зарплата по городам', 'verbose_name_plural': 'Зарплата по городам'},
        ),
        migrations.AlterModelOptions(
            name='cityvacancyshare',
            options={'verbose_name': 'Доля вакансий по городам', 'verbose_name_plural': 'Доля вакансий по городам'},
        ),
        migrations.AlterField(
            model_name='citysalary',
            name='city',
            field=models.CharField(max_length=100, unique=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='cityvacancyshare',
            name='city',
            field=models.CharField(max_length=100, unique=True, verbose_name='Город'),
        ),
    ]
