# Generated by Django 3.2.16 on 2025-01-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_ux_project', '0011_auto_20250114_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUXUISkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=100, verbose_name='Навык')),
                ('count', models.IntegerField(verbose_name='Количество упоминаний')),
            ],
            options={
                'verbose_name': 'Топ UX/UI Навыков',
                'verbose_name_plural': 'Топ UX/UI Навыков',
                'unique_together': {('year', 'skill')},
            },
        ),
    ]
